spring:
  data:
    mongodb:
#      host: localhost
#      host: 120.25.234.119
      host: 127.0.0.1
      port: 27017
      username: shi
      password: "123456"
      database: chatdb
  #    redis:
#      repositories:
#        enabled: false
  redis:
    database: 5
    host: 192.168.85.132
#    host: 120.25.234.119
    port: 6379
#    password: 123456
    password: root
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB
#logging:
#  level:
#    org.springframework.data.mongodb.core: DEBUG
socketio:
  port: 9999
  workCount: 100
  allowCustomRequests: true
  upgradeTimeout: 10000
  pingTimeout: 60000
  pingInterval: 25000
  maxHttpContentLength: 1048576
  maxFramePayloadLength: 1048576
server:
  port: 5555
#fastdfs:
#  nginx:
#    host: https://xxxxx/ # 更换为自己的域名


